image: Visual Studio 2017
install:
  - cinst fake
  # from https://stackoverflow.com/questions/33897161/appveyor-build-error-msb3774-could-not-find-sdk-microsoft-admediator-universal/33897162#33897162
  - ps: |
      Write-Host "Installing .NET SDK..."
      $msiPath = "$($env:USERPROFILE)\dotnet-SDK.exe"
      (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/c76aa823-bbc7-4b21-9e29-ab24ceb14b2d/9de2e14be600ef7d5067c09ab8af5063/dotnet-sdk-2.2.401-win-x64.exe', $msiPath)
      cmd /c start /wait $msiPath /quiet /norestart
      Write-Host "Installed" -ForegroundColor green

build_script:
  # See https://stackoverflow.com/a/12866669/1269722
  # Problem is that colors are lost
  # Don't blame me but powershell is the bigest crap on earth
  - cmd: fake.exe run build.fsx --parallel 3
  #- ps: .\build.cmd
#on_failure:
#  - appveyor PushArtifact FAKE.svclog
test: off
environment:
  PAKET_BOOTSTRAPPER_TRACE: true

#artifacts:
#  - path: 'nuget\dotnetcore\*.nupkg'
#    type: NuGetPackage
#  - path: 'nuget\legacy\*.nupkg'
#    type: NuGetPackage
#  - path: 'nuget\dotnetcore\Fake.netcore\*.zip'
#    type: Zip
