# Build and Release Pipeline

trigger:
- master
- release/next

pr:
- master
- release/next

stages:
- stage: CI
  dependsOn: []
  jobs:
  - job: CI
    pool:
      vmImage: 'windows-latest'
    continueOnError: false
    steps:
    - task: matthid.fsharp-helpers-extension-private.a2dadf20-1a83-4220-a4ee-b52f6c77f3cf.FAKE5@1
      displayName: 'Run the CI Build'
      inputs:
        FakeVersion: '5.15.4'
        ScriptArguments: '--parallel 3 -t CI'
- stage: Release_Github
  dependsOn: [ "CI" ]
  # condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
  #- job: ManualIntervention
  #  pool: server
  #  steps:
  #  - task: ManualIntervention@8
  #    inputs:
  #      instructions: 'Please approve in order to deploy as GitHub Release'
  - job: Deploy
    pool:
      vmImage: 'windows-latest'
    continueOnError: false
    environment: 'GitHub Release'
    variables:
      artifactsdirectory: $(Pipeline.Workspace)
    steps:
    - download: current
      artifact: windows-app
    - download: current
      artifact: windows-installer
    - download: current
      artifact: portable-files
    - task: matthid.fsharp-helpers-extension-private.a2dadf20-1a83-4220-a4ee-b52f6c77f3cf.FAKE5@1
      displayName: 'Run the Github Release'
      inputs:
        FakeVersion: '5.15.4'
        ScriptArguments: '--parallel 3 -t Release_Github'

